apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-deployment
  namespace: namespace-1
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: web-container
        image: registry.gitlab.com/shyambista/docker-images/devops-demo:24d0274
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: harbor-secret